<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>CommanderMarkers</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>Preview</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="builtin_marker_set_ids.json" />
    <EmbeddedResource Include="builtin_marker_set_ids.json" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Blish HUD" />
    <Reference Include="System.ComponentModel.Composition" />
    <Reference Include="MonoGame.Framework" />
    <Reference Include="Gw2Sharp" />
    <Reference Include="System.Core" />
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\working\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="MonoGame.Extended" />
    <Reference Include="System.Text.Json" />
  </ItemGroup>
</Project>