<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>MouseCursor</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>Preview</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Blish HUD" />
    <Reference Include="System.ComponentModel.Composition" />
    <Reference Include="MonoGame.Framework">
      <HintPath>..\..\working\MonoGame.Framework.dll</HintPath>
    </Reference>
    <Reference Include="Gw2Sharp" />
  </ItemGroup>
</Project>