namespace Oberyn.AnglerAssociate.Models
{
	public enum FishingHole
	{
		Any,
		AstralFish,
		BorealFish,
		BrackishJanthirFish,
		CavernFish,
		ChannelFish,
		CoastalFish,
		DeepFishingHole,
		DesertFish,
		DreamFish,
		FracturedChannelFish,
		FracturedDesertFish,
		FracturedFreshwaterFish,
		FracturedLakeFish,
		FreshwaterFish,
		GrottoFish,
		LakeFish,
		NayosianFish,
		NoxiousWaterFish,
		OffshoreFish,
		OpenWater,
		QuarryFish,
		RareFish,
		RiverFish,
		SaltwaterFish,
		ShinotaBlackfins,
		ShoreFish,
		SpireFish,
		VolcanicFish
	}
}
