namespace RaidClears.Features.Shared.Enums
{
	public static class Encounters
	{
		public enum RaidBosses
		{
			ValeGuardian,
			SpiritWoods,
			Gorseval,
			Sabetha,
			Slothasor,
			BanditTrio,
			Matthias,
			Escort,
			KeepConstruct,
			TwistedCastle,
			Xera,
			Cairn,
			MursaatOverseer,
			Samarog,
			Deimos,
			SoulessHorror,
			RiverOfSouls,
			StatuesOfGrenth,
			VoiceInTheVoid,
			ConjuredAmalgamate,
			TwinLargos,
			Qadim,
			Gate,
			Adina,
			Sabir,
			QadimThePeerless
		}

		public enum StrikeMission
		{
			ShiverpeaksPass,
			Fraenir,
			VoiceAndClaw,
			Whisper,
			Boneskinner,
			ColdWar,
			AetherbladeHideout,
			Junkyard,
			Overlook,
			HarvestTemple,
			OldLionsCourt
		}

		public enum Dungeons
		{
			AscalonianCatacombs,
			CaudecusManor,
			TwilightArbor,
			SorrowsEmbrace,
			CitadelOfFlame,
			HonorOfTheWaves,
			CrucibleOfEternity,
			RuinedCityOfArah
		}

		public enum DungeonPaths
		{
			AscalonianCatacombsStory,
			AscalonianCatacombsHodgins,
			AscalonianCatacombsDetha,
			AscalonianCatacombsTzark,
			CaudecusManorStory,
			CaudecusManorAsura,
			CaudecusManorSeraph,
			CaudecusManorButler,
			TwilightArborStory,
			TwilightArborLeurent,
			TwilightArborVevina,
			TwilightArborAetherPath,
			SorrowsEmbraceStory,
			SorrowsEmbraceFergg,
			SorrowsEmbraceRasalov,
			SorrowsEmbraceKoptev,
			CitadelOfFlameStory,
			CitadelOfFlameFerrah,
			CitadelOfFlameMagg,
			CitadelOfFlameRhiannon,
			HonorOfTheWavesStory,
			HonorOfTheWavesButcher,
			HonorOfTheWavesPlunderer,
			HonorOfTheWavesZealot,
			CrucibleOfEternityStory,
			CrucibleOfEternitySubmarine,
			CrucibleOfEternityTeleporter,
			CrucibleOfEternityFrontDoor,
			RuinedCityOfArahStory,
			RuinedCityOfArahJotun,
			RuinedCityOfArahMursaat,
			RuinedCityOfArahForgotten,
			RuinedCityOfArahSeer
		}
	}
}
